### ISSUE TITLE
Could not find a registered machine named 'tessel2'

### ISSUE THREAD

**Issue by Student007** [tessel/t2-vm#28]
For the case someone will have this problem:

```
Initializing VM...
(Replacing previous VM...)
VBoxManage: error: Could not find a registered machine named 'tessel2'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(VMName).raw(), machine.asOutParam())" at line 151 of file VBoxManageMisc.cpp
Unhandled rejection Error: 1
    at Object.ensureErrorObject (/usr/local/lib/node_modules/t2-vm/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/usr/local/lib/node_modules/t2-vm/node_modules/bluebird/js/main/promise.js:469:22)
    at /usr/local/lib/node_modules/t2-vm/node_modules/bluebird/js/main/promise.js:486:17
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/t2-vm/etc.js:47:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (child_process.js:1044:12)
```

The quick solution is:
1) change the line [103 of etc.js](https://github.com/tessel/t2-vm/blob/master/etc.js#L103) to something like  `exports.VM_NAME = 'T2';//'tessel2';`
2) (sudo) npm install -g

Problem should be fixed.
Hope this helps anyone :wink:

**Comment by Student007** [comment]
closed because it is a quick fix - no real issue.

**Comment by rwaldron** [comment]
@Student007 can you just make a PR for this?
