### ISSUE TITLE
http://storage.googleapis.com/tessel-builds/ccc157a289db14791ee7250733a0b7b5fb9c06c8.vdi isn't public

### ISSUE THREAD

**Issue by cflewis** [tessel/t2-vm#34]
Hi there,
I've gone through all the steps using a Google Compute Engine VM. I get as far as `t2-vm create`, but then it bards with this weird error. My guess is it's something about the fact the VM doesn't report having any USB ports? It does report having `eth0` so you would think that was OK.

```
[cflewis@belle]~❯ sudo t2-vm create
Initializing VM...
? Choose a bridge interface (or hit enter) eth0
Downloading image...
 downloaded ...
Creating VM...
VBoxManage: error: The medium '/home/cflewis/.tessel/vm.vdi' can't be used as the requested device type
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component Medium, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 178 of fil
e VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/home/cflewis/.tessel/vm.vdi"
Unhandled rejection Error: 1
    at Object.ensureErrorObject (/usr/local/lib/node_modules/t2-vm/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/usr/local/lib/node_modules/t2-vm/node_modules/bluebird/js/main/promise.js:469:22)
    at /usr/local/lib/node_modules/t2-vm/node_modules/bluebird/js/main/promise.js:486:17
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/t2-vm/etc.js:47:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

**Comment by cflewis** [comment]
The plot thickens:

```
[cflewis@belle]~❯ less ~/.tessel/vm.vdi
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Message></Error>
```

It looks like it's trying to access a GCS or S3 storage system that doesn't exist, or doesn't have public permission.

**Comment by cflewis** [comment]
Yep, that's the problem.

http://storage.googleapis.com/tessel-builds/ccc157a289db14791ee7250733a0b7b5fb9c06c8.vdi isn't public or doesn't exist, so the creation fails. Can someone poke around the bucket to see what's up?

**Comment by cflewis** [comment]
@johnnyman727 can you take a look please? You seem like a possible candidate to fix it :)

**Comment by cflewis** [comment]
Or @tcr ?

**Comment by tcr** [comment]
Hi! I'm responsible; we switched from Google Compute to Amazon S3 (and DO) after the transition from Technical Machine. I believe we just ran out of credits and this is our first casualty.

Here is a temporary link for the missing VM: https://www.dropbox.com/s/l19o2zdfdh5hn3l/vm.vdi?dl=0

I will build a new VM and host it on S3, then update this repo. Hope that helps.

**Comment by danfield73** [comment]
> Hi! I'm responsible; we switched from Google Compute to Amazon S3 (and DO) after the transition from Technical Machine. I believe we just ran out of credits and this is our first casualty.
> 
> Here is a temporary link for the missing VM: https://www.dropbox.com/s/l19o2zdfdh5hn3l/vm.vdi?dl=0
> 
> I will build a new VM and host it on S3, then update this repo. Hope that helps.

Hi - any update on this... your temp link is no longer working either?
