### ISSUE TITLE
Error: connect ENOENT /home/cflewis/.tessel/vm.port on create

### ISSUE THREAD

**Issue by cflewis** [tessel/t2-vm#35]
Related to #34 : 

I tried using the [VM image](https://www.dropbox.com/s/l19o2zdfdh5hn3l/vm.vdi?dl=1) given to me by @tcr , but it doesn't progress :(

Again I am scratching my head wondering if it's something to do with it itself being run in a cloud VM.

`touch`ing `vm.port` had no effect.

```
[cflewis@belle]~❯ sudo t2-vm create
Initializing VM...
(Replacing previous VM...)
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
? Choose a bridge interface (or hit enter) eth0
Downloading image...
........ downloaded ...
Creating VM...
Attaching to serial port: /home/cflewis/.tessel/vm.port
Configuring VM...
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: connect ENOENT /home/cflewis/.tessel/vm.port
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
```

**Comment by cflewis** [comment]
This was caused by VirtualBox not installing correctly. I manually ran the commands to see the errors from VirtualBox and fixed it.
