### ISSUE TITLE
Unable to create vm on windows 7

### ISSUE THREAD

**Issue by christianrossglobalia** [tessel/t2-vm#38]
The medium 'C:\Users\rossc.tessel\vm.vdi' can't be used as the requested device type.

Code d'erreur : 
E_FAIL (0x80004005)

Composant : 
MediumWrap

Interface : 
IMedium {4afe423b-43e0-e9d0-82e8-ceb307940dda}

Fonction appelée : 
IVirtualBox {0169423f-46b4-cde9-91af-1e9d5b6cd945}

Code retourné : 
VBOX_E_OBJECT_NOT_FOUND (0x80BB0001)

**Comment by little-dude** [comment]
Seeing the same.

## Environment:
- Archlinux (Kernel: 4.7.4-1)
- VirtualBox 5.1.6r110634

## Steps

```
~ ❯❯❯ t2 key generate
t2-vm create
t2-vm launch
Initializing VM...
(Replacing previous VM...)
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
? Choose a bridge interface (or hit enter) wlp3s0
Downloading image...
 downloaded ...
Creating VM...
VBoxManage: error: The medium '/home/corentih/.tessel/vm.vdi' can't be used as the requested device type
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 179 of file VBoxManageDisk
.cpp
VBoxManage: error: Invalid UUID or filename "/home/corentih/.tessel/vm.vdi"
Unhandled rejection Error: 1
    at Object.ensureErrorObject (/home/corentih/.npm-global/lib/node_modules/t2-vm/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/home/corentih/.npm-global/lib/node_modules/t2-vm/node_modules/bluebird/js/main/promise.js:472:22)
    at /home/corentih/.npm-global/lib/node_modules/t2-vm/node_modules/bluebird/js/main/promise.js:489:17
    at ChildProcess.<anonymous> (/home/corentih/.npm-global/lib/node_modules/t2-vm/etc.js:47:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
No VM found. Please run `t2-vm create` first
```

The disk image is downloaded correctly:

```
~/.tessel ❯❯❯ ls -al ~/.tessel
total 16
drwxr-xr-x 1 corentih corentih   76 Sep 21 22:22 .
drwxr-xr-x 1 corentih corentih 5602 Sep 21 22:36 ..
-rw------- 1 corentih corentih 1678 Sep 21 22:04 id_rsa
-rw------- 1 corentih corentih  391 Sep 21 22:04 id_rsa.pub
-rw-r--r-- 1 corentih corentih    3 Sep 21 21:58 preferences.json
-rw-r--r-- 1 corentih corentih  133 Sep 21 22:22 vm.vdi
```

I tried to manually remove the VM in virtualbox and create a new one using `~/.tessel/vm.vdi` as a hard drive and it failed in a similar way:
![vbox_tessel_fail](https://cloud.githubusercontent.com/assets/6646324/18737987/3371ec5a-804c-11e6-89b3-1b0a4ab6c3f1.png)
`VBoxManage` was unable to give any info about the disk:

```
~ ❯❯❯ VBoxManage showhdinfo ~/.tessel/vm.vdi
VBoxManage: error: The medium '/home/corentih/.tessel/vm.vdi' can't be used as the requested device type
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 179 of file VBoxManageDisk.cpp
```

For the record here is the md5sum of the disk:

```
~ ❯❯❯ md5sum ~/.tessel/vm.vdi
31b3fa3be13c3eca988b6647cf274003  /home/corentih/.tessel/vm.vdi
```

**Comment by little-dude** [comment]
Well that explains:

```
~ ❯❯❯ cat ~/.tessel/vm.vdi
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Message></Error>%
```

**Comment by little-dude** [comment]
duplicate of #34 then...
