### ISSUE TITLE
Tessel 2 virtual machine creation error

### ISSUE THREAD

**Issue by akkashaider** [tessel/t2-vm#41]
I am creating tessel 2 virtual machine on ubuntu 14.04 by using following command and getting errors

`t2-vm create`

I am getting following error message

```Downloading image...
downloaded ...
Creating VM...
VBoxManage: error: Could not get the storage format of the medium '/home/haider/.tessel/vm.vdi' (VERR_NOT_SUPPORTED)
VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 178 of file
VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/home/haider/.tessel/vm.vdi"
Unhandled rejection Error: 1
    at Object.ensureErrorObject (/home/haider/.npm-global/lib/node_modules/t2-vm/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/home/haider/.npm-global/lib/node_modules/t2-vm/node_modules/bluebird/js/main/promise.js:472:22)
    at /home/haider/.npm-global/lib/node_modules/t2-vm/node_modules/bluebird/js/main/promise.js:489:17
    at ChildProcess.<anonymous> (/home/haider/.npm-global/lib/node_modules/t2-vm/etc.js:47:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
```
I have installed all Prerequisites which includes nodejs, tessel-cli, tessel usb rules, virtual box and its extension pack. The versions are as follows
```
$ nodejs -v
v4.8.4
$ vboxmanage -v
5.0.40r115130
```

**Comment by gavriguy** [comment]
any update on this issue? I get the same error

**Comment by crazycodr** [comment]
Yeah i have this too, just trying tessel2-vm this morning, doesn't look good if it's been like that for months now...

**Comment by crazycodr** [comment]
The problem seems to be that the VDI image is invalid. If you try to import it into VBox directly, you get these details. Anyone know how the VDI image is generated? Maybe it's been bugged for sometime now?

```
Could not get the storage format of the medium '/home/thecrazycodr/.tessel/vm.vdi' (VERR_NOT_SUPPORTED).
```

Result Code: | VBOX_E_IPRT_ERROR (0x80BB0005)
-- | --
Component: | MediumWrap
Interface: | IMedium {ad47ad09-787b-44ab-b343-a082a3f2dfb1}
Callee: | IVirtualBox {d0a0163f-e254-4e5b-a1f2-011cf991c38d}
Callee RC: | VBOX_E_OBJECT_NOT_FOUND (0x80BB0001)

**Comment by crazycodr** [comment]
There we go, the problem is that the link to the VDI is invalid:

    http://storage.googleapis.com/tessel-builds/

```xml
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist.</Message>
</Error>
```

**Comment by danfield73** [comment]
Same issue still - the VDI is not hosted on googleapis anymore... anyone have a valid VDI or update on this issue?
